services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    UserBundle\:
        resource: '../../src/UserBundle/*'
        exclude: '../../src/UserBundle/{Entity,Repository}'

    UserBundle\Controller\:
        resource: '../../src/UserBundle/Controller'
        tags: ['controller.service_arguments']
