services:
  UserBundle\GlynnAdminMenu\UserMenuListener:
    autowire: true
    tags:
      - { name: 'kernel.event_listener', event: 'glynn_admin.menu_configure', method: 'onMenuConfigure', priority: -50 }
