services:
  GlyynnAdminBundle\Menu\MainBuilder:
    autowire: true
    tags:
      - { name: 'knp_menu.menu_builder', method: 'build', alias: 'glynn-admin' }

  GlyynnAdminBundle\Dashboard\DashboardExample:
    tags:
      - { name: 'kernel.event_listener', event: 'glynn_admin.dashboard_items', method: 'get' }

